//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extract.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Extract.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à on.
        /// </summary>
        public static string BuildAlarms_AlarmOn {
            get {
                return ResourceManager.GetString("BuildAlarms_AlarmOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build HMI alarm from.
        /// </summary>
        public static string BuildAlarms_BuildAlarmFrom {
            get {
                return ResourceManager.GetString("BuildAlarms_BuildAlarmFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Builder non compatible with.
        /// </summary>
        public static string BuildAlarms_BuilderNoCompatible {
            get {
                return ResourceManager.GetString("BuildAlarms_BuilderNoCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à do not compil.
        /// </summary>
        public static string BuildAlarms_CannotCompile {
            get {
                return ResourceManager.GetString("BuildAlarms_CannotCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create HMI alarm from.
        /// </summary>
        public static string BuildAlarms_CreateAlarm {
            get {
                return ResourceManager.GetString("BuildAlarms_CreateAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract HMI alarms from.
        /// </summary>
        public static string BuildAlarms_ExtractAlarmForm {
            get {
                return ResourceManager.GetString("BuildAlarms_ExtractAlarmForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No connexion found between.
        /// </summary>
        public static string BuildAlarms_NoConnexionDevice {
            get {
                return ResourceManager.GetString("BuildAlarms_NoConnexionDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and.
        /// </summary>
        public static string BuildAlarms_NoConnexionDeviceAnd {
            get {
                return ResourceManager.GetString("BuildAlarms_NoConnexionDeviceAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update HMI alarm from.
        /// </summary>
        public static string BuildAlarms_UpdateAlarm {
            get {
                return ResourceManager.GetString("BuildAlarms_UpdateAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HMI Alarms updated on.
        /// </summary>
        public static string BuildAlarms_UpdateOnDevice {
            get {
                return ResourceManager.GetString("BuildAlarms_UpdateOnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HMI alarm generation completed.
        /// </summary>
        public static string BuildAlarmsEnded {
            get {
                return ResourceManager.GetString("BuildAlarmsEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build canceled by user.
        /// </summary>
        public static string CancelByUser {
            get {
                return ResourceManager.GetString("CancelByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build alarms.
        /// </summary>
        public static string ContextMenu_BuildAlarms {
            get {
                return ResourceManager.GetString("ContextMenu_BuildAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build Folder tags.
        /// </summary>
        public static string ContextMenu_BuildFolderTags {
            get {
                return ResourceManager.GetString("ContextMenu_BuildFolderTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build HMI tags.
        /// </summary>
        public static string ContextMenu_BuildTags {
            get {
                return ResourceManager.GetString("ContextMenu_BuildTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string ContextMenu_Settings {
            get {
                return ResourceManager.GetString("ContextMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No alarm DB found in folder.
        /// </summary>
        public static string EmptyGlobalDb {
            get {
                return ResourceManager.GetString("EmptyGlobalDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alarms updated.
        /// </summary>
        public static string Feedback_AlarmsUpdated_Text {
            get {
                return ResourceManager.GetString("Feedback_AlarmsUpdated_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No projects found.
        /// </summary>
        public static string Feedback_NoProject_Text {
            get {
                return ResourceManager.GetString("Feedback_NoProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tack canceled by user.
        /// </summary>
        public static string TaskGenerateCancel {
            get {
                return ResourceManager.GetString("TaskGenerateCancel", resourceCulture);
            }
        }
    }
}
